/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=GeneratedBindings` (hash: d0fbf391aecf69015594d98126cfee35)
interface __BaseEnv_GeneratedBindings {
	INBOX_TOKENS: KVNamespace;
	DB: D1Database;
	EMAIL: SendEmail;
	ACCESS_AUD: "7b283d5d9b56f6fffa342280310a4ae68f13cbb05dc27f3c1d2faec2deae507a";
	ACCESS_TEAM_DOMAIN: "coryrankin.cloudflareaccess.com";
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiterDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RateLimiterDO";
	}
	interface Env extends __BaseEnv_GeneratedBindings {}
}
interface GeneratedBindings extends __BaseEnv_GeneratedBindings {}
